### PR TITLE
Allow creation of docker group with DOCKER_GID variable

### PR DESCRIPTION
**Pull request by sarthurdev**
Creates group if missing at runtime, uses su-exec to drop root for main executable.

#630

### CODE REVIEW

**Comment by dotneft** [comment]
What benefit of such approach?

**Comment by sarthurdev** [comment]
Without running the container running as root, the container needs the `docker` group to exist with the same GID as the host and it being given to the user with `--group-add` in order to access the socket.

Without this, you would either need to manually add the group each time the container is created by running `docker exec` or build an image adding the extra build step to add the group.

**Comment by dotneft** [comment]
but how su-exec helps with the problem? just add docker group is not enough?

**Comment by sarthurdev** [comment]
Sorry, nevermind! Going to close this as I found on further tests it's not actually necessary.

In my tests, I was having an issue using `--group-add docker` because it couldn't find the docker group in the container. However if you pass the docker group's GID instead of the name, it gave that group to the user and it could access the docker socket without actually needing to add a group inside the container.

**Comment by dotneft** [comment]
Great! Thank you for the information!

**Comment by sarthurdev** [comment]
Do you think there should be some documentation if someone else wants to run the docker plugin from within a container?

Example `docker run -v /var/run/docker.sock:/var/run/docker.sock --group-add <host docker GID> ... zabbix/zabbix-agent2:latest`

**Comment by dotneft** [comment]
Thank you! I will ask our template builders to include that into template documentation!

**Pull request closed without merging**
