### PR TITLE
Added curl to dockerimage

### PR DESCRIPTION
**Pull request by Brightside56**

### CODE REVIEW

**Comment by dotneft** [comment]
Why do you want to add curl?

**Comment by Brightside56** [comment]
I would like to use it in custom alertscripts, in my case it's slack notifications (webhook using curl)

**Comment by slabber** [comment]
I just opened and then closed an issue for this.

+1 for curl as I'm trying to do exactly the same - use slack notifications.

I'm using the alpine images btw

**Comment by frbayart** [comment]
Same use (alerting) and also use "jq" with some monitoring script to get a specific value.

**Comment by slabber** [comment]
With kubernetes another possibility is to do a postStart lifecycle hook:

Add this yaml to the server container section:

        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - apk update && apk add curl && apk upgrade

**Pull request closed without merging**
