### PR TITLE
mask some values in update_config_var

### PR DESCRIPTION
**Pull request by rockaut**

### CODE REVIEW

**Comment by dotneft** [comment]
Fixed Thank you for your help for project development! :-)

**Comment by rockaut** [comment]
You're welcome. Just out of curiosity: do you have a commit # how it got fixed?

**Comment by dotneft** [comment]
what do you mean?

**Comment by rockaut** [comment]
You haven't merged my branch but stated it got fixed.

**Comment by rockaut** [comment]
Nevermind found it.

**Comment by dotneft** [comment]
I slightly changed your patch. I did not use it because commit must be to master branch.

**Pull request closed without merging**
