### PR TITLE
Update Dockerfile with libapache2-mod-auth-radius

### PR DESCRIPTION
**Pull request by zohairraza**
add radius module

### CODE REVIEW

**Comment by dotneft** [comment]
Radius module is not required for default Zabbix installation. Feel free to add the module by yourself.

**Comment by zohairraza** [comment]
it doesnt allow to add modules later on because of sudo/root access

**Comment by dotneft** [comment]
use root account in this case.

**Comment by zohairraza** [comment]
I tried but is asking for password

**Comment by zohairraza** [comment]
zabbix@zabbix-zabbix-web-666576c968-86pmx: sudo apt-get install apache2 libapache2-mod-auth-radius
bash: sudo: command not found
zabbix@zabbix-zabbix-web-666576c968-86pmx:/usr/share/zabbix$ su root -c "apt-get install apache2 libapache2-mod-auth-radius"
Password:

**Comment by dotneft** [comment]
you need build your own image based on official one. Inside of your Dockerfile install anything what you want.

**Comment by zohairraza** [comment]
ok, will do it.. Thanks.
In EKS I preferred to use official images without modifications.

**Comment by dotneft** [comment]
Probably means not official from not trusted sources :-)

**Comment by zohairraza** [comment]
yeah.. and that is why I think there should be a way to allow customisation somehow in a running container. Maybe adding apt and a2enmod privilege to zabbix user ? 
it will make our lives much easier. Someone might need other tools for debugging or other modules.

**Comment by zohairraza** [comment]
anyone looking for a solution to this.

Building with official Dockerfiles you will encounter issues with build image access :

[internal] load metadata for docker.io/library/zabbix-build-mysql:ubuntu-6.0.26
ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

So I figured out another way using builder pattern and here is my Dockerfile:


####### Stage 1: Use the original ubuntu:jammy image as the base
FROM ubuntu:jammy as builder

####### Install required packages and enable Apache modules
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        apache2 \
        libapache2-mod-php \
        libapache2-mod-auth-radius && \
        groupadd \
            --system \
            --gid 1995 \
            zabbix && \
         useradd \
            --system \
            --comment "Zabbix monitoring system" \
            -g zabbix \
            --uid 1997 \
            --shell /sbin/nologin \
            --home-dir /var/lib/zabbix/ \
            zabbix && \
    rm -f /etc/apache2/sites-available/* && \
    rm -f /etc/apache2/sites-enabled/* && \
    /usr/sbin/a2enmod ssl && /usr/sbin/a2enmod auth_radius && \
    sed -ri \
            -e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' \
            -e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' \
        "/etc/apache2/apache2.conf" && \
    sed -ri \
            -e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' \
            -e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' \
        "/etc/apache2/conf-available/other-vhosts-access-log.conf" && \
    sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf && \
    sed -i 's/Listen 443/Listen 8443/g' /etc/apache2/ports.conf && \
    sed -i 's|/var/run/apache2$SUFFIX|/tmp|g' /etc/apache2/envvars

RUN chown --quiet -R zabbix:root /etc/apache2/ && \
    chgrp -R 0 /etc/apache2/ && \
    chmod -R g=u /etc/apache2/

####### Stage 2: Final stage
FROM zabbix/zabbix-web-apache-mysql:ubuntu-6.0-latest

####### Copy the installed packages and configurations from the builder stage
COPY --from=builder --chown=zabbix:root /etc/apache2 /etc/apache2
COPY --from=builder /usr/lib/apache2/modules /usr/lib/apache2/modules

**Pull request closed without merging**
